services:
  markly-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      MONGO_URI: "mongodb://mongo_bp:27017"
      BLUEPRINT_DB_USERNAME: ${BLUEPRINT_DB_USERNAME}
      BLUEPRINT_DB_ROOT_PASSWORD: ${BLUEPRINT_DB_ROOT_PASSWORD}
      PORT: 8080
    depends_on:
      - mongo_bp
    volumes:
      - backend_data:/app/data
    command: ["./api"]

  mongo_bp:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BLUEPRINT_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BLUEPRINT_DB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo_volume_bp:/data/db

volumes:
  mongo_volume_bp:
  backend_data:
