apiVersion: 1

alerting:
  - name: MarklyBackendAlerts
    type: file
    orgId: 1
    folder: 'Markly Backend'
    disableProvenance: false
    options:
      path: /etc/grafana/provisioning/alerting/rules
